// <auto-generated />
namespace LMS_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_file : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_file));
        
        string IMigrationMetadata.Id
        {
            get { return "202302241053011_update_file"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
