// <auto-generated />
namespace LMS_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatecertification1233123 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatecertification1233123));
        
        string IMigrationMetadata.Id
        {
            get { return "202303021033110_updatecertification1233123"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
